version: "3"

services:

  openapi-db:
    container_name: openapi-db
    image: postgres:16.1
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: openapi
  
  migrate:
    container_name: migrate
    image: migrate/migrate
    command: up -path /migrations -database postgresql://user:password@openapi-db:5432/openapi?sslmode=disable
    volumes:
      - ./migrations:/migrations
    depends_on:
      - openapi-db